### ISSUE TITLE
инструкция по запуску бота

### ISSUE THREAD

**Issue by tsvetkovpro** [stojanovic/conference-telegram-bot#1]
добрый день как я могу написать инструкцию к запуску вашего проекта. не найду апи ключ где менять и в каком окружении запускать бота.

**Comment by stojanovic** [comment]
Hey, instructions will be added soon.
Some steps are:
1. Check [Claudia Bot Builder](https://github.com/claudiajs/claudia-bot-builder), we are using that for bot builder.
2. Install Claudia.js globally.
3. Create Telegram bot with [BotFather](https://core.telegram.org/bots#6-botfather) and save the key.
4. Clone this repository, run `npm install`, then `claudia create --region eu-west-1 --configrure-telegram-bot` and folow the instructions (it'll show you webhook URL and ask for the key from step 4.)

Full instructions will be available soon in the readme.
